### ISSUE TITLE
Invalid IP detected error

### ISSUE THREAD

**Issue by Achus619** [chros73/rtorrent-ps#82]
sorry if this is a silly question, I tried looking around for similar cases but I think I am still too much of a noob :(
I set up rtorrent using the "Debian Install From Source - The Easy Way" doc on a ubuntu server 14.04 PC. I'm using the same session folder as my original rtorrent installation and I get the "invalid IP detected" error for just one tracker.
According to the tracker's support page, this error occurs when the client "is reporting an IP from one of the globally unroutable reserved subnets":
 IPv4 Reserved Subnets
         - 10.0.0.0/8
         - 172.16.0.0/12
         - 192.168.0.0/16
         - 169.254.0.0/16
         - 100.64.0.0/10
         - 127.0.0.0/8
 IPv6 Reserved Subnets
         - ::1/128
         - ::ffff/96
         - fe80::/10
         - fc00::/7
         - fec0::/16
         - 3ffe::/16
         - 2001:0db8::/32
         - 2001:0000::/32
         - 2002::/16

The other trackers on my session work just fine, and if I use the other rtorrent installation it all works and I don't get any errors. Also I appear as reachable on all my trackers with both installations.
Any tips? thanks

**Comment by chros73** [comment]
> original rtorrent installation

Which version is that exactly?

> this error occurs when the client "is reporting an IP from one of the globally unroutable reserved subnets"

Which subnet is that exactly (if it's not a secret)? Do you also use ipv6?

**Comment by Achus619** [comment]
> Which version is that exactly?

It's 0.9.6 according to rtorrent -h

> Which subnet is that exactly (if it's not a secret)? Do you also use ipv6?

I don't know :( I don't understand what it means that my client is "reporting an IP". I thought the only IP trackers knew about my server was my public IP, which is renewed every hour or so by my ISP. I've checked that IP (which looks like a normal public one) on the trackers connectable page and it all looks normal to me.
How can I find out this subnet? And why would it be different than the one the standard rtorrent uses?

**Comment by chros73** [comment]
> I thought the only IP trackers knew about my server was my public IP, which is renewed every hour or so by my ISP.

Is it an IPv4 address? (e.g. 31.185.34.98)
I guess so.

> why would it be different than the one the standard rtorrent uses?

:) Because git version (that my latest version is build upon) has already partial IPv6 support!
(It's not finished yet but it seems pretty stable. Rakshasa actively works on it.)
- it seems that the tracker in question supports both ipv4 and ipv6 connection (I don't use such a tracker)
- probably your linux distribution somehow assign a "valid" ipv6 address to the network adapters and rtorrent picks it up

Try out the following:
- set `network.bind_address.set` to your local (!) IPv4 address in rtorrent config (then restart rtorrent), this will disable IPv6 handling in current git version (until Rakshasa finishes the binding support), e.g.:
```ini
# The ip address the listening socket and outgoing connections is bound to. (bind)
network.bind_address.set = 192.168.1.34
```

Check the result with the tracker in question.

**Comment by Achus619** [comment]
It's working! bind_address didn't do much though, I had so set network.local_address.set to my local IP and then it got fixed. Weird huh?

anyways thank you so much for the help and all the work you do :)

**Comment by chros73** [comment]
Interesting, I'm glad it works.
